---
general-en:
  title: General Roman Calendar
  language: en
  sanctorale:
    - packaged: universal-en
    ## in order to load your custom calendar, place the file in data/
    ## and include it like this:
    # - file: universal-en.txt

general-la: &default
  title: Calendarium Romanum Generale
  language: la
  sanctorale:
    - packaged: universal-la

general-fr:
  title: Calendrier Général Romain
  language: fr
  sanctorale:
    - packaged: universal-fr

general-it:
  title: Calendario Romano Generale
  language: it
  sanctorale:
    - packaged: universal-it

general-es:
  title: Calendario Romano General
  language: es
  sanctorale:
    - packaged: universal-es


general-pt:
  title: Calendário Romano Geral
  language: pt
  sanctorale:
    - packaged: universal-pt



us: &us
  title: US Calendar
  language: en
  sanctorale:
    - packaged: universal-en
    - packaged: us-en
  temporale_extensions:
    - ThanksgivingUS
  transfer_to_sunday:
    - epiphany
    - ascension
    - corpus_christi

# The following entries define
# * common calendar of dioceses of United States
# * calendars for the specific US Diocese which observe the Ascension on the traditional date of Thursday
us-ascension: &us-ascension
  <<: *us
  title: US Calendar (Boston, Hartford, New York, Newark, Omaha, and Philadelphia)
  description: These Diocese have retained its celebration on the proper Thursday
  transfer_to_sunday:
    - epiphany
    - corpus_christi

us-boston:
  <<: *us-ascension

us-hartford:
  <<: *us-ascension

us-new-york:
  <<: *us-ascension

us-newark:
  <<: *us-ascension

us-omaha:
  <<: *us-ascension

us-philadelphia:
  <<: *us-ascension

# The following entries define
# * common calendar of dioceses of Czech Republic
# * calendars of it's both provinces - Bohemia and Moravia
# * calendar of each Bohemian and Moravian diocese
czech: &czech
  title: Český národní kalendář
  language: cs
  sanctorale:
    - packaged: czech-cs
  temporale_extensions:
    - ChristEternalPriest

czech-cechy: &czech-bohemia
  <<: *czech
  title: kalendář české církevní provincie
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-cechy-cs

czech-morava: &czech-moravia
  <<: *czech
  title: kalendář moravské církevní provincie
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-morava-cs

czech-pha:
  <<: *czech
  title: kalendář pražské arcidiecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-cechy-cs
    - packaged: czech-praha-cs

czech-ltm:
  <<: *czech
  title: kalendář litoměřické diecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-cechy-cs
    - packaged: czech-litomerice-cs

czech-hk:
  <<: *czech
  title: kalendář královéhradecké diecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-cechy-cs
    - packaged: czech-hradec-cs

czech-cb:
  <<: *czech
  title: kalendář českobudějovické diecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-cechy-cs
    - packaged: czech-budejovice-cs

czech-plz:
  <<: *czech
  title: kalendář plzeňské diecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-cechy-cs
    - packaged: czech-plzen-cs

czech-olm:
  <<: *czech
  title: kalendář olomoucké arcidiecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-morava-cs
    - packaged: czech-olomouc-cs

czech-brn:
  <<: *czech
  title: kalendář brněnské diecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-morava-cs
    - packaged: czech-brno-cs

czech-oo:
  <<: *czech
  title: kalendář ostravsko-opavské diecéze
  sanctorale:
    - packaged: czech-cs
    - packaged: czech-morava-cs
    - packaged: czech-ostrava-cs

default:
  <<: *default
